<a href="https://colab.research.google.com/github/amiskinis26/Coursework/blob/main/Data4700.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import numpy as np

In [2]:
parcels = pd.read_csv('/content/sample_data/Parcels.csv', low_memory = False)
parcels.head(1)
#parcel_number

,object_id,parcel_number,ward,address,council_district,zip_code,taxpayer_1,taxpayer_2,taxpayer_street,taxpayer_city,taxpayer_state,taxpayer_zip,property_class,property_class_desc,property_class_previous,use_code,use_code_desc,tax_status,tax_status_description,tax_status_previous,total_square_footage,total_acreage,frontage,depth,homestead_pre,nez,is_improved,num_bldgs,total_floor_area,style,year_built,sale_price,sale_date,assessed_value,assessed_value_previous,taxable_value,taxable_value_previous,economic_condition_factor_neigh,landmap,related,zoning,historic_designation,subdivision,legal_description,Shape__Area,Shape__Length
0,1,04000119.,4.0,541 W LAFAYETTE,6.0,48226,"SHEHAN, JOSEPH & LOUISE & WAYNE","KEARNEY, GAIL & GARCEAU, LYLA",3370 ROCKYCRUST,ROCHESTER HILLS,MI,48306,202.0,COMMERCIAL-VACANT,202.0,NaN,NaN,TAXABLE,TAXABLE,TAXABLE,13983.0,0.321,100.0,140.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,682100.0,681400.0,197316.0,187920.0,NaN,001,NaN,B5,NaN,NaN,S W LAFAYETTE 5&6 AND N 10 FT VAC ALLEY ADJ BL...,1.335122e-07,0.001486

In [8]:
parcels1 = parcels[["parcel_number",
                    "taxpayer_city",
                    "property_class",
                    "property_class_desc",
                    "tax_status",
                    "total_square_footage",
                    "total_acreage",
                    "frontage",
                    "depth",
                    "nez",
                    "num_bldgs",
                    "year_built",
                    "sale_price",
                    "sale_date",
                    "assessed_value_previous",
                    "taxable_value_previous"
                    ]]
parcels2 = parcels1[parcels1["property_class"].isin([401,402])]
parcels2.head(10)

,parcel_number,taxpayer_city,property_class,property_class_desc,tax_status,total_square_footage,total_acreage,frontage,depth,nez,num_bldgs,year_built,sale_price,sale_date,assessed_value_previous,taxable_value_previous
18,04002833.,DETROIT,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4922.0,0.113,40.0,124.0,Woodward - Calvert (H093),1.0,1914.0,0.0,NaN,19300.0,8695.0
19,04002832.,DETROIT,402.0,RESIDENTIAL-VACANT,TAXABLE,4351.0,0.100,35.0,124.0,Woodward - Calvert (H093),0.0,NaN,0.0,NaN,400.0,233.0
20,04002831.,DETROIT,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4356.0,0.100,35.0,124.0,Woodward - Calvert (H093),1.0,1912.0,22500.0,2019/02/27 00:00:00+00,15400.0,10954.0
21,04002766.,DETROIT,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4326.0,0.099,38.0,117.0,Woodward - Calvert (H093),1.0,1917.0,97000.0,2023/06/22 00:00:00+00,17700.0,15015.0
22,04002830.,DETROIT,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4356.0,0.100,35.0,124.0,Woodward - Calvert (H093),0.0,NaN,15000.0,2006/09/15 00:00:00+00,0.0,0.0
23,04002767.,ANN ARBOR,402.0,RESIDENTIAL-VACANT,TAXABLE,4095.0,0.094,35.0,117.0,Woodward - Calvert (H093),0.0,NaN,14000.0,1969/01/01 00:00:00+00,300.0,300.0
24,04002829.,DETROIT,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4356.0,0.100,35.0,124.0,Woodward - Calvert (H093),0.0,NaN,0.0,NaN,0.0,0.0
51,04002711.,DETROIT,402.0,RESIDENTIAL-VACANT,TAXABLE,12023.0,0.276,72.0,168.0,Boston Edison (H087),0.0,NaN,550.0,2005/06/29 00:00:00+00,6400.0,586.0
52,04002778.,DETROIT,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4661.0,0.107,40.0,117.0,Woodward - Calvert (H093),0.0,NaN,14500.0,2014/06/30 00:00:00+00,400.0,382.0
53,04002751.,DETROIT,401.0,RESIDENTIAL-IMPROVED,TAXABLE,11718.0,0.269,70.0,168.0,Boston Edison (H087),1.0,1912.0,200000.0,2020/04/28 00:00:00+00,109500.0,43034.0

In [4]:
parcels2.dtypes

parcel_number            object
taxpayer_city            object
property_class          float64
property_class_desc      object
tax_status               object
total_square_footage    float64
total_acreage           float64
frontage                float64
depth                   float64
nez                      object
num_bldgs               float64
year_built              float64
sale_price              float64
sale_date                object
assessed_value          float64
taxable_value           float64
dtype: object

In [9]:
parcels2["taxpayer_city"] = np.where(parcels2["taxpayer_city"] == "DETROIT", 1, 0)

<ipython-input-9-9c3a32c92788>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  parcels2["taxpayer_city"] = np.where(parcels2["taxpayer_city"] == "DETROIT", 1, 0)

In [ ]:
parcels2['sale_year'] = [x[:4] for x in parcels2['sale_date']]

TypeError: 'float' object is not subscriptable

In [10]:
parcels2.head(10)

,parcel_number,taxpayer_city,property_class,property_class_desc,tax_status,total_square_footage,total_acreage,frontage,depth,nez,num_bldgs,year_built,sale_price,sale_date,assessed_value_previous,taxable_value_previous
18,04002833.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4922.0,0.113,40.0,124.0,Woodward - Calvert (H093),1.0,1914.0,0.0,NaN,19300.0,8695.0
19,04002832.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4351.0,0.100,35.0,124.0,Woodward - Calvert (H093),0.0,NaN,0.0,NaN,400.0,233.0
20,04002831.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4356.0,0.100,35.0,124.0,Woodward - Calvert (H093),1.0,1912.0,22500.0,2019/02/27 00:00:00+00,15400.0,10954.0
21,04002766.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4326.0,0.099,38.0,117.0,Woodward - Calvert (H093),1.0,1917.0,97000.0,2023/06/22 00:00:00+00,17700.0,15015.0
22,04002830.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4356.0,0.100,35.0,124.0,Woodward - Calvert (H093),0.0,NaN,15000.0,2006/09/15 00:00:00+00,0.0,0.0
23,04002767.,0,402.0,RESIDENTIAL-VACANT,TAXABLE,4095.0,0.094,35.0,117.0,Woodward - Calvert (H093),0.0,NaN,14000.0,1969/01/01 00:00:00+00,300.0,300.0
24,04002829.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4356.0,0.100,35.0,124.0,Woodward - Calvert (H093),0.0,NaN,0.0,NaN,0.0,0.0
51,04002711.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,12023.0,0.276,72.0,168.0,Boston Edison (H087),0.0,NaN,550.0,2005/06/29 00:00:00+00,6400.0,586.0
52,04002778.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4661.0,0.107,40.0,117.0,Woodward - Calvert (H093),0.0,NaN,14500.0,2014/06/30 00:00:00+00,400.0,382.0
53,04002751.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,11718.0,0.269,70.0,168.0,Boston Edison (H087),1.0,1912.0,200000.0,2020/04/28 00:00:00+00,109500.0,43034.0